sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t manjinder50/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manjinder50/docker-react npm run test
